update Unit Test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,12 +1,29 @@
 name: main
 on: [push]
 jobs:
-  build:
+  job1:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
 
-    - name: Print text from file.txt
-      run: cat dist/index.js
+    - name: Setup Node.js
+      uses: actions/setup-node@v2
+      with:
+        node-version: '18'
+
+    - name: Run Test1
+      run: |
+        output=$(node dist/Test1.js)
+        # Capture the exit code of the previous command
+        exit_code=$output
+  
+        # Check the exit code to determine if there was an error
+        if [ $exit_code -ne 0 ]; then
+          echo "Error: The Node.js script failed with exit code $exit_code"
+          # You can add more error-handling actions here if needed
+          exit 1  # Exit the workflow with an error code
+        fi
+  
+
 
